### ISSUE TITLE
New `gpg` keys for build.ros.org

### ISSUE THREAD

**Issue by kw90** [RobInLabUJI/ROSLab#2]
The keys used to build ROS packages we're swapped in the ROS build farm after a [security incident](https://discourse.ros.org/t/security-issue-on-ros-build-farm/9342).

The old key `421C365BD9FF1F717815A3895523BAEEB01FA116` [should be replaced](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454) by the new key `C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654`. The Dockerfile generated by ROSLab should also import that key in order for the image to build.

Thank you for this awesome framework that makes my life easier and for considering this issue. :)

**Comment by ecervera** [comment]
Thank you for pointing it out. I will take care of it as soon as possible.
Glad to know that you use the software ;)

**Comment by ecervera** [comment]
I have updated the keys in the "develop" and "web" branches.
Thanks again!
